.TH "Antenna" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Antenna
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SAR\&.h>\fP
.SH "Detailed Description"
.PP 
\fBAntenna\fP can act as tranmitter or reciever\&. As tranmitter, it takes the signal and creates an incident field\&. As reciever, it integrates the field incident on the antenna support\&. 
.PP
Definition at line 80 of file SAR\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
