.TH "C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/Target_Generator Directory Reference" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/Target_Generator Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInput\&.h\fP"
.br
.ti -1c
.RI "file \fBPrototypes\&.h\fP"
.br
.ti -1c
.RI "file \fBTargetCreator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTargetEditor\&.cpp\fP"
.br
.in -1c
