.TH "ChebyshevGrid" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChebyshevGrid
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Image_Recovery\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 146 of file Image_Recovery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
