.TH "DataGenerator" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataGenerator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Data_Generator\&.h>\fP
.PP
Inherited by \fBDataGenerator2d\fP\fC [private]\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 22 of file Data_Generator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
