.TH "Data2d" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data2d
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Data_Generator\&.h>\fP
.PP
Inherits Data\&.
.SH "Detailed Description"
.PP 
Definition at line 66 of file Data_Generator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
