.TH "Data_Generator/Data_Generator.cpp" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data_Generator/Data_Generator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Data_Generator\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 9 of file Data_Generator\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
