.TH "Testing/Data_Generation_Unit_Test.cpp" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Testing/Data_Generation_Unit_Test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'input\&.h'\fP
.br
\fC#include 'data_generation\&.h'\fP
.br
\fC#include 'image_recovery\&.h'\fP
.br
\fC#include <ofstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBphi\fP (double x1, double x2, double y1, double y2)"
.br
.ti -1c
.RI "double \fBf\fP (double y1, double y2)"
.br
.ti -1c
.RI "double \fBpsi\fP (double x1, double x2, double y1, double y2)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fBOutput_Weights\fP (ostream os, complex< double > *weights, int l)"
.br
.ti -1c
.RI "void \fBOutput_Grids\fP (ostream os, double *grids)"
.br
.ti -1c
.RI "void \fBTest_Grid_Creation\fP ()"
.br
.ti -1c
.RI "void \fBTest_Indexing\fP (ofstream log)"
.br
.ti -1c
.RI "void \fBTest_Image_Loading\fP ()"
.br
.ti -1c
.RI "void \fBTest_Data_Generation\fP ()"
.br
.ti -1c
.RI "void \fBTest_Data_Loading\fP ()"
.br
.ti -1c
.RI "void \fBTest_Image_Recovery\fP ()"
.br
.ti -1c
.RI "void \fBTest_Image_Output\fP ()"
.br
.ti -1c
.RI "void \fBTest_Chebyshev_Interpolation\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double f (double y1, double y2)"

.SS "int main (int argc, char * argv[])"
\fBTest_Image_Output()\fP; 
.PP
Definition at line 15 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Output_Grids (ostream os, double * grids)\fC [inline]\fP"

.PP
Definition at line 68 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Output_Weights (ostream os, complex< double > * weights, int l)\fC [inline]\fP"

.PP
Definition at line 56 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "double phi (double x1, double x2, double y1, double y2)"

.SS "double psi (double x1, double x2, double y1, double y2)"

.SS "void Test_Chebyshev_Interpolation ()\fC [inline]\fP"

.PP
Definition at line 117 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Data_Generation ()\fC [inline]\fP"

.PP
Definition at line 103 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Data_Loading ()\fC [inline]\fP"

.PP
Definition at line 106 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Grid_Creation ()\fC [inline]\fP"

.PP
Definition at line 85 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Image_Loading ()\fC [inline]\fP"

.PP
Definition at line 99 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Image_Output ()\fC [inline]\fP"

.PP
Definition at line 112 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Image_Recovery ()\fC [inline]\fP"

.PP
Definition at line 109 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Indexing (ofstream log)\fC [inline]\fP"

.PP
Definition at line 93 of file Data_Generation_Unit_Test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
