.TH "C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/Data_Generator/Data_Generator.cpp" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/Data_Generator/Data_Generator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Data_Generator\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 9 of file Data_Generator\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
