.TH "Data_Generator/Data_Generator.h" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data_Generator/Data_Generator.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataGenerator\fP"
.br
.ti -1c
.RI "class \fBDataGenerator2d\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const complex< double > \fBi\fP (0, 1)"
.br
.ti -1c
.RI "complex< double > \fBf\fP (point y, complex< double > *d)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBpi\fP =3\&.14159265359"
.br
.ti -1c
.RI "const double \fBc_0\fP =299792458"
.br
.ti -1c
.RI "const int \fBN\fP =4"
.br
.ti -1c
.RI "const int \fBM\fP =\fBN\fP*\fBN\fP"
.br
.ti -1c
.RI "const int \fBK\fP =1"
.br
.ti -1c
.RI "const double \fBimage_height\fP =0"
.br
.ti -1c
.RI "\fBDataGenerator2d\fP \fBformat\fP ='RAW'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "complex<double> f (point y, complex< double > * d)"

.PP
Definition at line 17 of file Data_Generator\&.h\&.
.SS "const complex<double> i (0, 1)"

.SH "Variable Documentation"
.PP 
.SS "const double c_0 =299792458"

.PP
Definition at line 3 of file Data_Generator\&.h\&.
.SS " \fBDataGenerator2d\fP format ='RAW'"
The data that we would collect physically\&. Data may have several dimensions\&. For example, there are three polarizations, slow time, fast time, flight pass, etc\&. Data can eithe be representedin frequency domain, or time domain\&. Typically if data is given in frequency domain, then for each pulse(slowtime bin), The collected data has a windowed Fourier transform aplied to it\&. This is either done in hardward, digitally\&. 
.SS "const double image_height =0"

.PP
Definition at line 13 of file Data_Generator\&.h\&.
.SS "const int K =1"

.PP
Definition at line 11 of file Data_Generator\&.h\&.
.SS "const int M =\fBN\fP*\fBN\fP"

.PP
Definition at line 7 of file Data_Generator\&.h\&.
.SS "const int N =4"

.PP
Definition at line 6 of file Data_Generator\&.h\&.
.SS "const double pi =3\&.14159265359"

.PP
Definition at line 2 of file Data_Generator\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
