.TH "DataGenerator2d" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataGenerator2d \- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!//  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Data_Generator\&.h>\fP
.PP
Inherits \fBDataGenerator\fP\&.
.SH "Detailed Description"
.PP 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!// 
.PP
Definition at line 34 of file Data_Generator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
