.TH "Image_Recovery/Image_Recoverer.h" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image_Recovery/Image_Recoverer.h
.SH SYNOPSIS
.br
.PP
\fC#include <complex>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImageRecoverer\fP"
.br
.ti -1c
.RI "class \fBImagingPlane\fP"
.br
.RI "The plane that\&. "
.ti -1c
.RI "class \fBImageRecoverer2d\fP"
.br
.ti -1c
.RI "class \fBImageRecoverer3d\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
