.TH "Image_Recovery/Image_Recoverer.cpp" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image_Recovery/Image_Recoverer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'image_recovery\&.h'\fP
.br
\fC#include 'input\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc=1, char *filenames[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc = \fC1\fP, char * filenames[])"

.PP
Definition at line 7 of file Image_Recoverer\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
