.TH "Image_Recovery/Image_Recoverer_Direct.h" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image_Recovery/Image_Recoverer_Direct.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImageRecovererDirect\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBImage_Recovery_Direct\fP (double *recovered_reflectivity, complex< double > *data, ostream &log)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Image_Recovery_Direct (double * recovered_reflectivity, complex< double > * data, ostream & log)"

.PP
Definition at line 12 of file Image_Recoverer_Direct\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
