.TH "C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/Image_Recovery/Image_Recovery.cpp" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/Image_Recovery/Image_Recovery.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'input\&.h'\fP
.br
\fC#include 'image_recovery\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc=1, char *filenames[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc = \fC1\fP, char * filenames[])"

.PP
Definition at line 6 of file Image_Recovery\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
