.TH "ImageRecoverer" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageRecoverer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Image_Recoverer\&.h>\fP
.PP
Inherited by \fBImageRecoverer2d\fP\fC [private]\fP, \fBImageRecoverer3d\fP\fC [private]\fP, and \fBImageRecovererDirect\fP\fC [private]\fP\&.
.SH "Detailed Description"
.PP 
Take a given sar system and convert its collected data into an estimate for the object that create that data\&. This is an abstract class\&. Actually recoverying and image depends on the geometry of the scenario and collected data\&. 
.PP
Definition at line 13 of file Image_Recoverer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
