.TH "ImageRecoverer2d" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageRecoverer2d
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Image_Recoverer\&.h>\fP
.PP
Inherits \fBImageRecoverer\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 33 of file Image_Recoverer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
