.TH "ImageRecovererDirect" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageRecovererDirect
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Image_Recoverer_Direct\&.h>\fP
.PP
Inherits \fBImageRecoverer\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 10 of file Image_Recoverer_Direct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
