.TH "Math" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Math
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Math\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 5 of file Math\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
