.TH "point" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Target\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset\fP (double xp, double yp)"
.br
.ti -1c
.RI "\fBpoint\fP ()"
.br
.ti -1c
.RI "\fBpoint\fP (double xp, double yp)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Target\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "point::point ()\fC [inline]\fP"

.PP
Definition at line 25 of file Target\&.h\&.
.SS "point::point (double xp, double yp)\fC [inline]\fP"

.PP
Definition at line 26 of file Target\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void point::set (double xp, double yp)\fC [inline]\fP"

.PP
Definition at line 24 of file Target\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double point::x"

.PP
Definition at line 23 of file Target\&.h\&.
.SS "double point::y"

.PP
Definition at line 23 of file Target\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
