.TH "Rect" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rect
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SAR\&.h>\fP
.PP
Inherits \fBSignal\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 65 of file SAR\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
