.TH "lib/SAR.h" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/SAR.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSAR\fP"
.br
.ti -1c
.RI "class \fBSignal\fP"
.br
.RI "Represents the signal that the antenna will modulate and apply as a current to the\&. "
.ti -1c
.RI "class \fBChirp\fP"
.br
.ti -1c
.RI "class \fBRect\fP"
.br
.ti -1c
.RI "class \fBAntenna\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
