.TH "SAR" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAR
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SAR\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual point \fBflight_path\fP (double t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAntenna\fP \fBantenna\fP"
.br
.ti -1c
.RI "\fBSignal\fP \fBp\fP"
.br
.ti -1c
.RI "Carrier \fBw0\fP"
.br
.ti -1c
.RI "float \fBpulse_rate\fP"
.br
.ti -1c
.RI "float \fBsample_rate\fP"
.br
.ti -1c
.RI "Data \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file SAR\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual point SAR::flight_path (double t)\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBAntenna\fP SAR::antenna"

.PP
Definition at line 18 of file SAR\&.h\&.
.SS "Data SAR::data"

.PP
Definition at line 25 of file SAR\&.h\&.
.SS "\fBSignal\fP SAR::p"

.PP
Definition at line 20 of file SAR\&.h\&.
.SS "float SAR::pulse_rate"

.PP
Definition at line 22 of file SAR\&.h\&.
.SS "float SAR::sample_rate"

.PP
Definition at line 23 of file SAR\&.h\&.
.SS "Carrier SAR::w0"

.PP
Definition at line 21 of file SAR\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
