.TH "Signal" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Signal \- Represents the signal that the antenna will modulate and apply as a current to the\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SAR\&.h>\fP
.PP
Inherited by \fBChirp\fP\fC [private]\fP, and \fBRect\fP\fC [private]\fP\&.
.SH "Detailed Description"
.PP 
Represents the signal that the antenna will modulate and apply as a current to the\&. 
.PP
Definition at line 33 of file SAR\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
