.TH "Target2dS" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Target2dS
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Target\&.h>\fP
.PP
Inherits \fBTarget\fP\&.
.SH "Detailed Description"
.PP 
A sampled 2d target, consist of a collection of samples of the reflectivity function\&. These samples are used to evaluate teh relfectivity function using some interpolation method\&. 
.PP
Definition at line 27 of file Target\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
