.TH "Target" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Target
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Target\&.h>\fP
.SH "Detailed Description"
.PP 
A target represents a physical entity that we would scatter an incident field\&. Curently, targets are assumed stationary\&. Should relax this latter\&. Subclasses include sampled targets, and function targets\&. A function target takes in a point and returns the reflectivity at that point\&. 
.PP
Definition at line 8 of file Target\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
