.TH "Target_Generator/TargetCreator.cpp" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Target_Generator/TargetCreator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int arg_count, char *arguments[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int arg_count, char * arguments[])"

.PP
Definition at line 13 of file TargetCreator\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
