.TH "C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/lib/Target.h" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/lib/Target.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTarget\fP"
.br
.ti -1c
.RI "class \fBpoint\fP"
.br
.ti -1c
.RI "class \fBTarget2dS\fP"
.br
.ti -1c
.RI "class \fBTarget3dS\fP"
.br
.ti -1c
.RI "class \fBTarget2dF\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "complex< double > \fBf\fP (\fBpoint\fP y, complex< double > *d)"
.br
.RI "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!// "
.ti -1c
.RI "complex< double > \fBp\fP (double w)"
.br
.ti -1c
.RI "complex< double > \fBinterp\fP (complex< double > *d, double sl, double qj)"
.br
.ti -1c
.RI "double \fBphi\fP (\fBpoint\fP x, \fBpoint\fP y)"
.br
.ti -1c
.RI "double \fBGamma_X\fP (double s)"
.br
.ti -1c
.RI "double \fBGamma_Y\fP (double s)"
.br
.ti -1c
.RI "int \fBSize_Of_Support\fP (double *reflectivity)"
.br
.ti -1c
.RI "void \fBLoadTarget\fP (string name)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "complex<double> f (\fBpoint\fP y, complex< double > * d)"

.PP
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!// !!!!!!!!!!!!!!!!!!Input functions!!!!!!!!!!!!!!!!!!!!!!!!!!!// 
.PP
Definition at line 71 of file Input\&.h\&.
.SS "double Gamma_X (double s)"

.PP
Definition at line 41 of file Input\&.h\&.
.SS "double Gamma_Y (double s)"

.PP
Definition at line 45 of file Input\&.h\&.
.SS "complex<double> interp (complex< double > * d, double sl, double qj)"

.PP
Definition at line 56 of file Input\&.h\&.
.SS "void LoadTarget (string name)"

.PP
Definition at line 52 of file Target\&.h\&.
.SS "complex<double> p (double w)"

.PP
Definition at line 62 of file Input\&.h\&.
.SS "double phi (\fBpoint\fP x, \fBpoint\fP y)"

.PP
Definition at line 50 of file Input\&.h\&.
.SS "int Size_Of_Support (double * reflectivity)"

.PP
Definition at line 43 of file Target\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
