.TH "Target2dS" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Target2dS
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Target\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 35 of file Target\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
