.TH "Target3dS" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Target3dS
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Target\&.h>\fP
.PP
Inherits \fBTarget\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 56 of file Target\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
