.TH "lib/Target.h" 3 "Tue May 2 2017" "Version .101" "SITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Target.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTarget\fP"
.br
.ti -1c
.RI "class \fBTarget2dS\fP"
.br
.ti -1c
.RI "class \fBTarget3dS\fP"
.br
.ti -1c
.RI "class \fBTarget2dF\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "complex< double > \fBf\fP (point y, complex< double > *d)"
.br
.ti -1c
.RI "complex< double > \fBp\fP (double w)"
.br
.ti -1c
.RI "complex< double > \fBinterp\fP (complex< double > *d, double sl, double qj)"
.br
.ti -1c
.RI "double \fBphi\fP (point x, point y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "complex<double> f (point y, complex< double > * d)"

.PP
Definition at line 17 of file Data_Generator\&.h\&.
.SS "complex<double> interp (complex< double > * d, double sl, double qj)"

.SS "complex<double> p (double w)"

.SS "double phi (point x, point y)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SITS from the source code\&.
