.TH "C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/test/test.h" 3 "Mon May 1 2017" "Version .001" "Sythetic Aperture Radar Image Testing Suite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/cygwin64/home/ez pawn/Projects, simulation, and code/SITS/test/test.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTest_Grid_Creation\fP ()"
.br
.RI "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!// "
.ti -1c
.RI "void \fBTest_Indexing\fP ()"
.br
.ti -1c
.RI "void \fBTest_Image_Loading\fP ()"
.br
.ti -1c
.RI "void \fBTest_Data_Generation\fP ()"
.br
.ti -1c
.RI "void \fBTest_Data_Loading\fP ()"
.br
.ti -1c
.RI "void \fBTest_Image_Recovery\fP ()"
.br
.ti -1c
.RI "void \fBTest_Image_Output\fP ()"
.br
.ti -1c
.RI "void \fBPrint_Grids\fP (double *grids)"
.br
.ti -1c
.RI "void \fBPrint_Weights\fP (complex< double > *weights, int l)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Print_Grids (double * grids)\fC [inline]\fP"

.SS "void Print_Weights (complex< double > * weights, int l)\fC [inline]\fP"

.SS "void Test_Data_Generation ()\fC [inline]\fP"

.PP
Definition at line 103 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Data_Loading ()\fC [inline]\fP"

.PP
Definition at line 106 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Grid_Creation ()\fC [inline]\fP"

.PP
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!// 
.PP
Definition at line 85 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Image_Loading ()\fC [inline]\fP"

.PP
Definition at line 99 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Image_Output ()\fC [inline]\fP"

.PP
Definition at line 112 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Image_Recovery ()\fC [inline]\fP"

.PP
Definition at line 109 of file Data_Generation_Unit_Test\&.cpp\&.
.SS "void Test_Indexing ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sythetic Aperture Radar Image Testing Suite from the source code\&.
